# Generated by Django 4.2.7 on 2023-11-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classmates', '0003_alter_classmate_address_alter_classmate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmate',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='', max_length=6),
        ),
    ]
